version: '2.1'
services:
  invoice_php:
    build: ./docker/php
    container_name: invoice_php
    volumes:
      - ./invoices:/data/www
    networks:
      - invoice_network
    working_dir: /data/www
  invoice_php_xdebug:
    container_name: invoice_php_xdebug
    build: ./docker/php
    volumes:
      - ./invoices:/data/www
      - ./docker/php/xdexdebugbug.ini:/usr/local/etc/php/conf.d/xdebug.ini:cached
    networks:
      - invoice_network
    working_dir: /data/www
  invoice_mysql:
    container_name: invoice_mysql
    image: mysql:5.7.33
    environment:
      - MYSQL_DATABASE=invoices_db
      - MYSQL_RANDOM_ROOT_PASSWORD=1
      - MYSQL_USER=no_root
      - MYSQL_PASSWORD=123qweASD
    ports:
      - 3308:3306
    networks:
      - invoice_network
  invoice_amqp:
    container_name: invoice_amqp
    image: rabbitmq:alpine
    ports:
      - 5673:5672
    environment:
      - RABBITMQ_DEFAULT_VHOST=invoices_host
    networks:
      - invoice_network
  amqp_management:
    container_name: invoice_amqp_management
    image: rabbitmq:3-management
    ports:
      - 15675:15672
    networks:
      - invoice_network
networks:
  invoice_network:
    ipam:
      config:
        - subnet: 172.90.0.0/16
          ip_range: 172.99.5.0/24
