framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        # failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
             async:
                 dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                 options:
                   auto_setup: true
                   exchange:
                     name: messages
                   queues:
                     invoices: ~
            # failed: 'doctrine://default?queue_name=failed'
#             sync: 'sync://'

        routing:
            # Route your messages to the transports
             'App\Message\InvoiceGeneratorMessage': async
