monolog:
  channels: [messenger_audit]
  handlers:
    main:
      type: stream
      path: "%kernel.logs_dir%/%kernel.environment%.log"
      level: debug
      channels: ["!event"]
    messenger:
      type: stream
      path: "%kernel.logs_dir%/mail.log"
      level: debug
      channels: ["messenger_audit"]
    console:
      type: console
      process_psr_3_messages: false
      channels: ["!event", "!doctrine", "!console"]
